# Basic
title: WWmore
subtitle: Blog
description: Welcome to my blog~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: WWmore
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: å»ºç­‘å‡ ä½• / Python
url: "http://wwmore.github.io"

# Comment
comment:
    disqus: WWmore
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: WWmore_H
    github: WWmore
    # twitter:
    mail: i1103552872@gmail.com

# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id: 27207f71af608ec9abe4831b177e72b8

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-112392965-1
    host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Search
search: 

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}

# Comments
disqus:
disqus_url: 'https://WWmore.disqus.com/embed.js'

# Tags è®¾ç½®æ ‡ç­¾
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value


 #SNS settings é…ç½®ç¤¾äº¤ç½‘ç«™url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/huihui-blue'
  zhihu: '//https://www.zhihu.com/people/wang-hui-hui-31-75/activities'
  #douban: '//'
  github: '//github.com/WWmore'


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value
